AWSTemplateFormatVersion: "2010-09-09"

Description: "世界一丁寧なAWS解説をCloudformationでコード化”

# AWSの各リソースの定義

Resources:
# VPCの定義
RaiseTech-VPC:
	Type: AWS::EC2::VPC
Properties:
	CidrBlock:10.0.0.0/16
	EnableDnsHostnames:true
	EnableDnsSupport:true
	Tags:
	-Key:Name
	Value:raisetech-vpc

# サブネットの定義
RaiseTech-PublicSubnet1a
	Type: AWS::EC2::Subnet
	Properties:
    CiderBlock:10.0.0.0/24
    AvailabilityZone:ap-northeast-1a
    VpcId:!Ref RaiseTech-VPC
    # サブネット単位でipv4パブリックアドレスの割り当てを有効化
    MapPublicIpOnLaunch:true
    Tags:
      -Key:Name
      Value:raisetech-public-subnet-1a
	Metadata:
   AWS:CloudFormation::Designer:
    id: d7aa5763-884d-474d-a58e-e89846f7075a

RaiseTech-VPCPublicSubnet1d:
  Type:AWS::EC2::Subnet
  Properties:
   CidrBlock:10.0.3.0/24
   AvailabilityZone:ap-northeast-1d
   VpcId:!Ref RaiseTech-VPC

   # サブネット単位でipv4パブリックアドレスの割り当てを有効化
   MapPublicIpOnLaunch:true
   Tags:
    -Key:Name
     Value:raisetechvpc-public-subnet-1d
     Metadata:
      AWS::CloudFormation::Designer:
        id: 53a3c8ff-60b2-4ebd-ac3f-af8f5d477e33

# RDS用プライベートサブネット1dの定義
RaiseTechvpcrdsSubnet1d:
  Type:AWS::EC2::Subnet
  Properties:
    CidrBlock:10.0.1.0/24
    AvailabilityZone:ap-northeast-1d
    VpcId:!Ref RaiseTechVPC
    Tags:
    -Key:Name
    Value:raisetech-vpc-rds-private-subnet-1d
  Metadata:
    AWS::CloudFormation::Designer:
     id:431e856f-cdba-4222-b438-198e1bd44938

# RDS用プライベートサブネット1cの定義
RaiseTechvpcrdsSubnet1c:
  Type:AWS::EC2::Subnet
  Properties:
    CidrBlock:10.0.0.0/24
    AvailabilityZone:ap-northeast-1c
    VpcId:!Ref RaiseTechVPC
    Tags:
    -Key:Name
    Value:raisetech-vpc-rds-private-subnet-1c
  Metadata:
    AWS::CloudFormation::Designer:
     id:09b01ebb-8e43/416e-81a8-60fc6b4dac8a

# インターネットゲートウェイの定義
RaiseTech-VPCIgw:
  Type: AWS::EC2::InternetGateway
  Properties:
    Tags:
     -Key:Name
     Value:raisetech-vpc-igw

# VPCGatewayAttachment定義
RaiseTech-VPCGatewayAttachment:
  Type:AWS::EC2::VPCGatewayAttachment
  Properties:
    VpcId:!Ref RaiseTechVPC
    InternetGatewayId: !Ref RaiseTech-vpcIgw

#ルートテーブルの定義
RaiseTech-VPCRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
   VpcId: !Ref RaiseTechVPC
   Tags:
    - Key:Name
      Value:raisetechvpc-route-table
# サブネットとルートテーブルの関連付け
RaiseTechVPCRouteLocal1a:






