version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: Run cfn-lint for CloudFormation
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml  # 構文チェック

  deploy_vpc:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Deploy VPC CloudFormation Stack
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/1_VPC_Network_v2.yml \
              --stack-name ${VPC_STACK_NAME} \
              --capabilities CAPABILITY_NAMED_IAM  # IAMリソースの作成や変更を許可
              --region ${AWS_REGION}

  deploy_ec2_alb:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - aws-cli/install 
      - run:
          name: Deploy EC2 and ALB CloudFormation Stack
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/2_EC2_ALB_v2.yml \
              --stack-name ${EC2_STACK_NAME} \
              --capabilities CAPABILITY_NAMED_IAM
              --region ${AWS_REGION}

  deploy_rds_s3:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Deploy RDS and S3 CloudFormation Stack
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/3_RDS_S3_v2.yml \
              --stack-name ${RDS_STACK_NAME} \
              --capabilities CAPABILITY_NAMED_IAM
              --region ${AWS_REGION}

workflows:
  version: 2
  deploy:
    jobs:
      - cfn-lint
      - deploy_vpc:
          requires:
            - cfn-lint
      - deploy_ec2_alb:
          requires:
            - deploy_vpc
      - deploy_rds_s3:
          requires:
            - deploy_ec2_alb ##
