version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.2.3
  ruby: circleci/ruby@2.1.4

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy to aws from template
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/1_VPC_Network.yml--stack-name Lec13-VPC
            aws cloudformation deploy --template-file cloudformation/2_EC2_ALB.yml.--stack-name Lec13-EC2--capabilities CAPABILITY_NAMED_IAM --parameter-overrides MyKeyPair=${MY_KEY_PAIR} MyIP=${MY_IP}
            aws cloudformation deploy --template-file cloudformation/3_RDS_S3.yml--stack-name Lec13-RDS

  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:jlGm9c9LijRGEdj8We+ozU0wfDeQTK7cK4GPVPvMwCA"
      - ansible-playbook/install:
          version:2.9.23
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user -i ansible/inventory --private-key ~/.ssh/id_rsa
  execute-serverspec:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: 3.2.3
      - ruby/install-deps:
          app-dir: serverspec
      - run:
          name: execute
          command: |
            cd serverspec
            rake spec 
workflows:
  workflow:
    jobs:
      - execute-cloudformation
      - execute-ansible:
          requires:
            - execute-cloudformation
      - execute-serverspec:
          requires:
            - execute-ansible
