version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: Run cfn-lint for CloudFormation
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml  # 構文チェック

  deploy_all_stacks:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Deploy all CloudFormation Stacks
          command: |
            set -x
            aws cloudformation deploy
              --template-file cloudformation/1_VPC_Network_EIP.yml
              --stack-name ${VPC_STACK_NAME}
              --region ${AWS_REGION} 
            aws cloudformation deploy
              --template-file cloudformation/2_EC2_ALB_EIP.yml
              --stack-name ${EC2_STACK_NAME}
              --capabilities CAPABILITY_NAMED_IAM
              --parameter-overrides MyKeyPair=${MY_KEY_PAIR} MyIP=${MY_IP}
              --region ${AWS_REGION}
            aws cloudformation deploy
              --template-file cloudformation/3_RDS_S3_v2.yml
              --stack-name ${RDS_STACK_NAME}
              --region ${AWS_REGION}
workflows:
  version: 2
  deploy:
    jobs:
      - cfn-lint
      - deploy_all_stacks:
          requires:
            - cfn-lint
