version: 2.1
orbs:
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@5.1.0

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: Deploy to aws from template
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/1_VPC_Network.yml--stack-name Lec13-VPC
            aws cloudformation deploy --template-file cloudformation/2_EC2_ALB.yml.--stack-name Lec13-EC2--capabilities CAPABILITY_NAMED_IAM --parameter-overrides MyKeyPair=${MY_KEY_PAIR} MyIP=${MY_IP}
            aws cloudformation deploy --template-file cloudformation/3_RDS_S3.yml--stack-name Lec13-RDS

  deploy_cloudformation:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:GexUfnERzqL8QYP/ZQSvjJvbAkgtgh5bn/PfSzTo8Vw"
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user -i ansible/inventory --private-key ~/.ssh/id_rsa
  execute-serverspec:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: 3.2.3
      - ruby/install-deps:
          app-dir: serverspec
      - run:
          name: Deploy CloudFormation Stacks
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/1_VPC_Network_EIP.yml \
              --stack-name Lec13-VPC

            aws cloudformation deploy \
              --template-file cloudformation/2_EC2_ALB_EIP.yml \
              --stack-name Lec13-EC2 \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides MyKeyPair=${MY_KEY_PAIR} MyIP=${MY_IP}

            aws cloudformation deploy \
              --template-file cloudformation/3_RDS_S3_v2.yml \
              --stack-name Lec13-RDS

  run_ansible_playbook:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: pip install ansible
      - run:
          name: Run Ansible Playbook
          command: ansible-playbook -i /home/taemimizukura/GitHub/RaiseTech/.ansible/hosts.ini /home/taemimizukura/GitHub/RaiseTech/.ansible/myrole/tasks/main.yml

workflows:
  build:
    jobs:
      - cfn-lint
      - deploy_cloudformation:
          requires: [cfn-lint]
      - run_ansible_playbook:
          requires: [deploy_cloudformation]
